include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    constant_identifier_names: ignore
    close_sinks: ignore
    missing_required_param: error
    type_annotate_public_apis: ignore
    inference_failure_on_function_return_type: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_dynamic_calls: ignore
    use_setters_to_change_properties: ignore
    inference_failure_on_function_invocation: ignore
    strict_raw_type: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    one_member_abstracts: ignore
    no_default_cases: ignore
    unnecessary_this: ignore

  exclude:
    - lib/src/**.g.dart
    - lib/src/**.gr.dart
    - lib/src/**.config.dart

linter:
  rules:
    public_member_api_docs: false
    unrelated_type_equality_checks: false
