name: poke_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  awesome_dio_interceptor: ^1.2.0
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  envied: ^0.5.4+1  
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.2
  json_annotation: ^4.9.0
  provider: ^6.1.2

dev_dependencies:
  auto_route_generator: ^8.0.0
  envied_generator: ^0.5.4+1
  flutter_flavorizr: ^2.2.3
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/img/app/
